bbcode_default:
    template: 
        route: symbb_bbcode_template_angular_default
        params: 
            file: 'bbcode'
            
bbcode_signature:
    template: 
        route: symbb_bbcode_template_angular_signature
        params: 
            file: 'bbcode'