language: php

php:
  - 5.4
  - 5.5
  
services:
  - memcached # will start memcached

before_script: 
  - apt-get install php5-memcached
  - composer self-update
  - composer install --dev --prefer-source

notifications:
  email: christianwielath@googlemail.com
