_symbb_index:
    pattern:  /
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }
    
symbb_forum_index:
    pattern:  /
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }
        
symbb_api_forum:
    resource: "@SymBBCoreForumBundle/Controller"
    type: annotation