symbb_forum_index:
    pattern:  /forum/
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }
        
symbb_api_forum:
    resource: "@SymBBCoreForumBundle/Controller"
    type: annotation