services:
    symbb.core.forum.breadcrumb:
        twig.extension.symbb.core.forum.breadcrumb:
        class: SymBB\Core\ForumBundle\Twig\BreadcrumbExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension } 
            
    symbb.core.forum.topic.data:
        twig.extension.symbb.core.forum.topic.data:
        class: SymBB\Core\ForumBundle\Twig\TopicDataExtension
        arguments: ['@doctrine.orm.symbb_entity_manager', '@knp_paginator', '@service_container', '@symbb.core.forum.topic.flag']
        tags:
            - { name: twig.extension } 
            
    symbb.core.forum.data:
        twig.extension.symbb.core.forum.data:
        class: SymBB\Core\ForumBundle\Twig\ForumDataExtension
        arguments: ['@symbb.core.forum.flag']
        tags:
            - { name: twig.extension } 
            
    symbb.core.forum.flag:
        class: SymBB\Core\ForumBundle\DependencyInjection\ForumFlagHandler
        arguments: ['@doctrine.orm.symbb_entity_manager', '@symbb.core.user.manager', '@security.context', '@memcache.default']
        
    symbb.core.forum.topic.flag:
        class: SymBB\Core\ForumBundle\DependencyInjection\TopicFlagHandler
        arguments: ['@doctrine.orm.symbb_entity_manager', '@symbb.core.user.manager', '@security.context', '@memcache.default']
        calls:
            - [setForumFlagHandler, ["@symbb.core.forum.flag"]]
            
    symbb.core.forum.notify:
        class: SymBB\Core\ForumBundle\DependencyInjection\NotifyHandler
        arguments: ['@service_container']