services:
    symbb.core.forum.breadcrumb:
        twig.extension.symbb.core.forum.breadcrumb:
        class: SymBB\Core\ForumBundle\Twig\BreadcrumbExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension } 
    symbb.core.forum.topic.data:
        twig.extension.symbb.core.forum.topic.data:
        class: SymBB\Core\ForumBundle\Twig\TopicDataExtension
        arguments: ['@doctrine.orm.symbb_entity_manager', '@knp_paginator', '@service_container', '@symbb.core.forum.topic.flag']
        tags:
            - { name: twig.extension } 
    symbb.core.forum.topic.flag:
        class: SymBB\Core\ForumBundle\DependencyInjection\TopicFlagHandler
        arguments: ['@doctrine.orm.symbb_entity_manager', '@fos_user.user_manager', '@security.context', '@memcache.default']