services:
    symbb.core.forum.breadcrumb:
        twig.extension.symbb.core.forum.breadcrumb:
        class: SymBB\Core\ForumBundle\Twig\BreadcrumbExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension } 
            
    symbb.core.forum.topic.data:
        twig.extension.symbb.core.forum.topic.data:
        class: SymBB\Core\ForumBundle\Twig\TopicDataExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension } 
            
    symbb.core.forum.data:
        twig.extension.symbb.core.forum.data:
        class: SymBB\Core\ForumBundle\Twig\ForumDataExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension } 
            
    symbb.core.forum.managers.twig:
        twig.extension.symbb.core.forum.managers.twig:
        class: SymBB\Core\ForumBundle\Twig\ManagerExtension
        arguments: ['@symbb.core.post.manager', '@symbb.core.forum.manager']
        tags:
            - { name: twig.extension } 
            
    symbb.core.forum.manager:
        class: SymBB\Core\ForumBundle\DependencyInjection\ForumManager
        arguments: ['@security.context', '@symbb.core.topic.flag', '@symbb.core.post.flag', '@symbb.core.config.manager', '@doctrine.orm.symbb_entity_manager', '@knp_paginator']
    
    symbb.core.post.manager:
        class: SymBB\Core\ForumBundle\DependencyInjection\PostManager
        arguments: ['@security.context', '@symbb.core.post.flag', '@symbb.core.config.manager', '@doctrine.orm.symbb_entity_manager', '@event_dispatcher', '@knp_paginator']
        
    symbb.core.topic.manager:
        class: SymBB\Core\ForumBundle\DependencyInjection\TopicManager
        arguments: ['@security.context', '@symbb.core.topic.flag', '@symbb.core.config.manager', '@doctrine.orm.symbb_entity_manager', '@event_dispatcher']
            
    symbb.core.forum.flag:
        class: SymBB\Core\ForumBundle\DependencyInjection\ForumFlagHandler
        arguments: ['@doctrine.orm.symbb_entity_manager', '@symbb.core.user.manager', "@symbb.core.access.manager", '@security.context', '@memcache.default']
        
    symbb.core.topic.flag:
        class: SymBB\Core\ForumBundle\DependencyInjection\TopicFlagHandler
        arguments: ['@doctrine.orm.symbb_entity_manager', '@symbb.core.user.manager', "@symbb.core.access.manager", '@security.context', '@memcache.default']
        calls:
            - [setForumFlagHandler, ["@symbb.core.forum.flag"]]
            
    symbb.core.post.flag:
        class: SymBB\Core\ForumBundle\DependencyInjection\PostFlagHandler
        arguments: ['@doctrine.orm.symbb_entity_manager', '@symbb.core.user.manager', "@symbb.core.access.manager", '@security.context', '@memcache.default']
        calls:
            - [setForumFlagHandler, ["@symbb.core.forum.flag"]]
            
    symbb.core.forum.notify:
        class: SymBB\Core\ForumBundle\DependencyInjection\NotifyHandler
        arguments: ['@service_container']
        
    symbb.core.forum.acl.manager:
        class: SymBB\Core\ForumBundle\Acl\Manager
        tags:
            - { name: symbb.acl.manager }
            
    symbb.core.forum.config:
        class: SymBB\Core\ForumBundle\EventListener\ConfigListener
        tags:
            - { name: kernel.event_listener, event: symbb.config.configs, method: configs }