symbb_user_options:
    pattern:  /ucp/options
    defaults: { _controller: SymBBCoreUserBundle:Option:index }
    
symbb_user_options_security:
    pattern:  /ucp/options/security
    defaults: { _controller: SymBBCoreUserBundle:Option:security }