symbb_user_options:
    pattern:  /user/options
    defaults: { _controller: SymBBCoreUserBundle:Option:index }
    
symbb_user_options_security:
    pattern:  /user/options/security
    defaults: { _controller: SymBBCoreUserBundle:Option:security }