symbb_user_options:
    pattern:  /options
    defaults: { _controller: SymBBCoreUserBundle:Option:index }
    
symbb_user_options_security:
    pattern:  /options/security
    defaults: { _controller: SymBBCoreUserBundle:Option:security }
    
symbb_user_userlist:
    pattern:  /userlist
    defaults: { _controller: SymBBCoreUserBundle:Info:userlist }