services:
    symbb.core.user.data:
        twig.extension.symbb.core.user.data:
        class: SymBB\Core\UserBundle\Twig\UserDataExtension
        tags:
            - { name: twig.extension } 
    symbb.core.user.access:
        class: SymBB\Core\UserBundle\DependencyInjection\UserAccess
        arguments: ["@doctrine.orm.symbb_entity_manager", "@security.context", "@security.acl.provider"]
    symbb.core.user.access.twig:
        twig.extension.symbb.core.user.access:
        class: SymBB\Core\UserBundle\Twig\AccessExtension
        arguments: ['@symbb.core.user.access']
        tags:
            - { name: twig.extension } 