_symbbcoresitebundle_site_list:
    pattern:  /site/list
    defaults: { _controller: SymBBCoreSiteBundle:AcpSite:list }

_symbbcoresitebundle_site_new:
    pattern:  /site/new
    defaults: { _controller: SymBBCoreSiteBundle:AcpSite:new}
    
_symbbcoresitebundle_site_edit:
    pattern:  /site/{id}/edit
    defaults: { _controller: SymBBCoreSiteBundle:AcpSite:edit }
    
_symbbcoresitebundle_site_sort:
    pattern:  /site/sort
    defaults: { _controller: SymBBCoreSiteBundle:AcpSite:sort }
    
_symbbcoresitebundle_site_remove:
    pattern:  /site/{id}/remove
    defaults: { _controller: SymBBCoreSiteBundle:AcpSite:remove }


_symbbcoresitebundle_navigation_list:
    pattern:  /site/{site}/navigation/list
    defaults: { _controller: SymBBCoreSiteBundle:AcpNavigation:list }

_symbbcoresitebundle_navigation_new:
    pattern:  /site/{site}/navigation/new
    defaults: { _controller: SymBBCoreSiteBundle:AcpNavigation:new}

_symbbcoresitebundle_navigation_edit:
    pattern:  /site/navigation/{id}/edit
    defaults: { _controller: SymBBCoreSiteBundle:AcpNavigation:edit }

_symbbcoresitebundle_navigation_remove:
    pattern:  /site/navigation/{id}/remove
    defaults: { _controller: SymBBCoreSiteBundle:AcpNavigation:remove }


_symbbcoresitebundle_navigation_item_list:
    pattern:  /navigation/{navigation}/item/list
    defaults: { _controller: SymBBCoreSiteBundle:AcpNavigationItem:list }

_symbbcoresitebundle_navigation_item_new:
    pattern:  /navigation/{navigation}/item/new/{parent}
    defaults: { _controller: SymBBCoreSiteBundle:AcpNavigationItem:newItem}

_symbbcoresitebundle_navigation_item_edit:
    pattern:  /navigation/item/{id}/edit
    defaults: { _controller: SymBBCoreSiteBundle:AcpNavigationItem:edit }

_symbbcoresitebundle_navigation_item_sort:
    pattern:  /navigation/item/sort
    defaults: { _controller: SymBBCoreSiteBundle:AcpNavigationItem:sort }

_symbbcoresitebundle_navigation_item_remove:
    pattern:  /navigation/item/{id}/remove
    defaults: { _controller: SymBBCoreSiteBundle:AcpNavigationItem:remove }