fm_bbcode:
      filter_sets:
        default:
          locale: %locale%
          xhtml: true
          filters: [ default ]
        signature:
          locale: %locale%
          xhtml: true
          filters: [ default ]