fm_bbcode:
      filter_sets:
        default:
          locale: %locale%
          xhtml: true
          filters: [ default, Block, Email, Image, List, Quote, Text, Url, Video ]
        signature:
          locale: %locale%
          xhtml: true
          filters: [ default, Block, Email, Image, Quote, Url ]