lsw_memcache:
    session:
        client: default
    clients:
        default:
            options:
                # important if we have more than one symbb installations!
                prefix_key: %secret% 
            hosts:
              - { dsn: localhost, port: 11211 }