services:
    symbb_table_prefix:
        class: SymBB\Core\ConfigBundle\EventListener\DoctrineNameListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, connection: symbb }