services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    symbb.core.table.prefix:
        class: SymBB\Core\ConfigBundle\EventListener\DoctrineNameListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, connection: symbb }
    symbb.core.config.template:
        twig.extension.symbb.core.config.template:
        class: SymBB\Core\ConfigBundle\DependencyInjection\TwigTemplateConfigExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
    symbb.core.user.data:
        twig.extension.symbb.core.user.data:
        class: SymBB\Core\UserBundle\Twig\UserDataExtension
        tags:
            - { name: twig.extension } 