sym_bb_core_config:
    usermanager:
      user_class: SymBB\Core\UserBundle\Entity\User
    database:
      table_prefix: 
        prod: symbb_
        dev:  symbb_dev_
        test: symbb_test_
    