sym_bb_core_config:
    database:
      table_prefix: 
        prod: symbb_
        dev:  symbb_dev_
        test: symbb_test_
    template: 
      acp: SymBBTemplateAcpBundle
      forum: SymBBTemplateSimpleBundle
      portal: SymBBTemplateSimpleBundle
    