services:
    symbb.listener.post.survey.template:
        class: SymBB\Extension\SurveyBundle\EventListener\TemplateListener
        tags:
            - { name: kernel.event_listener, event: symbb.post.template.form.options.tabs, method: addPostTab }
            - { name: kernel.event_listener, event: symbb.post.template.form.options.tabcontents, method: addPostTabContent }
            - { name: kernel.event_listener, event: symbb.topic.template.form.options.tabs, method: addTopicTab }
            - { name: kernel.event_listener, event: symbb.topic.template.form.options.tabcontents, method: addTopicTabContent }
    symbb.listener.post.survey.form:
        class: SymBB\Extension\SurveyBundle\EventListener\FormListener
        tags:
            - { name: kernel.event_listener, event: symbb.post.controller.form, method: addPostFormPart }