services:
    symbb.listener.post.rating:
        class: SymBB\Extension\RatingBundle\EventListener\TemplateListener
        tags:
            - { priority: -255, name: kernel.event_listener, event: symbb.post.template.after.text, method: afterText }
            - { name: kernel.event_listener, event: symbb.topic.template.stylesheets, method: topicStylesheets }
   
    symbb.extensionrating.util:
        twig.extension.symbb.extensionrating.util:
        class: SymBB\Extension\RatingBundle\Twig\UtilExtension
        arguments: ['@doctrine', '@security.context']
        tags:
            - { name: twig.extension } 
            
    symbb.extensionrating.acl.manager:
        class: SymBB\Extension\RatingBundle\Acl\Manager
        tags:
            - { name: symbb.acl.manager }