services:
    symbb.template.default.form:
        twig.extension.symbb.template.default.form:
        class: SymBB\Template\DefaultBundle\Twig\FormExtension
        tags:
            - { name: twig.extension } 
            
    symbb.listener.site.template.default:
        class: SymBB\Template\DefaultBundle\EventListener\SiteListener
        tags:
            - { name: kernel.event_listener, event: symbb.site.template.choices, method: templateChoices }
