liip_imagine:
    filter_sets:
        symbb_forum_bg:
            quality: 100
            filters:
                strip: ~
                relative_resize: { heighten: 218  }  
                symbb_opacity: { opacity: 80 } 