services:
    symbb.template.simple.form:
        twig.extension.symbb.template.simple.form:
        class: SymBB\Template\SimpleBundle\Twig\FormExtension
        tags:
            - { name: twig.extension } 
            
    symbb.listener.config.template.simple:
        class: SymBB\Template\SimpleBundle\EventListener\ConfigListener
        tags:
            - { name: kernel.event_listener, event: symbb.config.defaults, method: defaults }
            - { name: kernel.event_listener, event: symbb.config.choices, method: choices }
            - { name: kernel.event_listener, event: symbb.config.type, method: type }
            - { name: kernel.event_listener, event: symbb.config.section, method: section }
