_symbb_acp:
    pattern:  /acp/
    defaults: { _controller: SymBBCoreForumBundle:Acp:list }
    
_symbbcoreforumbundle_forum_list:
    pattern:  /acp/forum/list
    defaults: { _controller: SymBBCoreForumBundle:Acp:list }
    
_symbbcoreforumbundle_forum_list_child:
    pattern:  /acp/forum/list/{parent}
    defaults: { _controller: SymBBCoreForumBundle:Acp:list }

_symbbcoreforumbundle_forum_new:
    pattern:  /acp/forum/new/forum
    defaults: { _controller: SymBBCoreForumBundle:Acp:new }

_symbbcoreforumbundle_forum_edit:
    pattern:  /acp/forum/edit/{id}
    defaults: { _controller: SymBBCoreForumBundle:Acp:edit }
    
_symbbcoreforumbundle_forum_new_category:
    pattern:  /acp/forum/new/category
    defaults: { _controller: SymBBCoreForumBundle:Acp:newCategory }
    
_symbbcoreforumbundle_forum_new_link:
    pattern:  /acp/forum/new/link
    defaults: { _controller: SymBBCoreForumBundle:Acp:newLink }
    
_symbbcoreforumbundle_forum_sort:
    pattern:  /acp/forum/sort
    defaults: { _controller: SymBBCoreForumBundle:Acp:sort }
    
_symbbcoreforumbundle_forum_remove:
    pattern:  /acp/forum/remove/{id}
    defaults: { _controller: SymBBCoreForumBundle:Acp:remove }
    
_symbbcoreuserbundle_group_access:
    pattern:  /acp/access/group/{step}
    defaults: { _controller: SymBBCoreUserBundle:AcpAccess:group }