symbb_login:
    pattern:  /login
    defaults: { _controller: SymBBFOSUserBundle:Security:login }
    
symbb_logout:
    pattern:  /logout
    defaults: { _controller: SymBBFOSUserBundle:Security:logout }
    
symbb_register:
    pattern:  /register
    defaults: { _controller: SymBBFOSUserBundle:Registration:register }
    
symbb_imprint:
    pattern:  /imprint
    defaults: { _controller: SymBBCoreSystemBundle:StaticPage:imprint }
    
symbb_terms:
    pattern:  /terms
    defaults: { _controller: SymBBCoreSystemBundle:StaticPage:terms }
    
    