_imagine:
    resource: .
    type:     imagine
    
JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /_trans

SymBBExtensionBundle_Extra:
    resource: .
    prefix: /{_locale}/
    type: extra
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    prefix: /{_locale}/

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /{_locale}/resetting
 
_symbb_acp_routings:
    resource: "@SymBBCoreSystemBundle/Resources/config/routing/acp.yml"
    prefix: /{_locale}/acp
    
_symbb_frontend_routings:
    resource: "@SymBBCoreSystemBundle/Resources/config/routing/frontend.yml"
    prefix: /{_locale}/
    
 