_imagine:
    resource: .
    type:     imagine

SymBBExtensionBundle_Extra:
    resource: .
    type: extra
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
 
fos_message:
    resource: "@FOSMessageBundle/Resources/config/routing.xml"
    prefix: /messages
 
_symbb_acp_routings:
    resource: "@SymBBCoreSystemBundle/Resources/config/routing/acp.yml"
    prefix: /acp
    
_symbb_frontend_routings:
    resource: "@SymBBCoreSystemBundle/Resources/config/routing/frontend.yml"
    
_symbb_core_user:
    resource: "@SymBBCoreUserBundle/Resources/config/routing.yml"
    prefix: /ucp
    
_symbb_core_forum:
    resource: "@SymBBCoreForumBundle/Resources/config/routing.yml"
    
_symbb_core_install:
    resource: "@SymBBCoreInstallBundle/Resources/config/routing.yml"
 