services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
            
    symbb.core.table.prefix:
        class: SymBB\Core\SystemBundle\EventListener\DoctrineNameListener
        arguments: ['@service_container']
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata, connection: symbb }
            
    symbb.core.config.template:
        twig.extension.symbb.core.config.template:
        class: SymBB\Core\SystemBundle\DependencyInjection\TwigTemplateConfigExtension
        arguments: ['@service_container']
        tags:
            - { name: twig.extension }
            
    symbb.core.access.manager:
        class: SymBB\Core\SystemBundle\DependencyInjection\AccessManager
        arguments: ["@doctrine.orm.symbb_entity_manager", "@security.context", "@security.acl.provider"]
        
    symbb.core.config.manager:
        class: SymBB\Core\SystemBundle\DependencyInjection\ConfigManager
        arguments: ["@doctrine.orm.symbb_entity_manager", '@event_dispatcher']
        
        
    symbb.listener.config.system:
        class: SymBB\Core\SystemBundle\EventListener\ConfigListener
        tags:
            - { name: kernel.event_listener, event: symbb.config.defaults, method: defaults }
            - { name: kernel.event_listener, event: symbb.config.type, method: type }
            
    symbb.extension.routing_loader:
        class: SymBB\ExtensionBundle\Routing\ExtraLoader
        arguments: ["@kernel"]
        tags:
            - { name: routing.loader } 
    
    symbb.core.imagine.filter.loader.symbb_opacity:
        class: SymBB\Core\SystemBundle\Imagine\Filter\Loader\OpacityFilterLoader
        arguments: ["@liip_imagine", "%kernel.root_dir%"]
        tags:
            - { name: liip_imagine.filter.loader , loader: symbb_opacity }
        