fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SymBB\Core\UserBundle\Entity\User
    model_manager_name: symbb
    group:
        group_class: SymBB\Core\UserBundle\Entity\Group