services:
    symbb.core.angular.listener.template:
        class: SymBB\Core\AngularBundle\EventListener\TemplateListener
        arguments: ['@symbb.core.angular.router']
        tags:
            - { name: kernel.event_listener, event: symbb.template.global.javascripts, method: javascripts, priority: 50 }
            
    symbb.core.angular.router:
        class: SymBB\Core\AngularBundle\DependencyInjection\Router
        arguments: ['@event_dispatcher', '@router']
        
    symbb.core.angular.routing_loader:
        class: SymBB\Core\AngularBundle\Routing\AdvancedLoader
        arguments: ['@symbb.core.angular.router']
        tags:
            - { name: routing.loader }