services:
    fos_message.message_manager.default:
        class: FOS\MessageBundle\EntityManager\MessageManager
        tags:
            - { name: form.type, alias: symbb_fos_user_registration }
        arguments: ['@doctrine.orm.symbb_entity_manager', '%fos_message.message_class%', '%fos_message.message_meta_class%']
    fos_message.thread_manager.default:
        class: FOS\MessageBundle\EntityManager\ThreadManager
        tags:
            - { name: form.type, alias: symbb_fos_user_registration }
        arguments: ['@doctrine.orm.symbb_entity_manager', '%fos_message.thread_class%', '%fos_message.thread_meta_class%', '@fos_message.message_manager']