services:   
    symbb.listener.config.template.test:
        class: SymBB\Template\TestBundle\EventListener\ConfigListener
        tags:
            - { name: kernel.event_listener, event: symbb.config.choices, method: choices }
