services:
    symbb.listener.post.bbcode.editor:
        class: SymBB\Extension\BBCodeBundle\EventListener\TemplateListener
        tags:
            - { name: kernel.event_listener, event: symbb.topic.template.stylesheets, method: stylesheets }
            - { name: kernel.event_listener, event: symbb.topic.template.javascripts, method: javascripts }
            - { name: kernel.event_listener, event: symbb.post.template.stylesheets, method: stylesheets }
            - { name: kernel.event_listener, event: symbb.post.template.javascripts, method: javascripts }
    symbb.listener.post.bbcode.form:
        class: SymBB\Extension\BBCodeBundle\EventListener\FormListener
        tags:
            - { name: kernel.event_listener, event: symbb.post.controller.form, method: getPostFormType }
            - { name: kernel.event_listener, event: symbb.topic.controller.form, method: getTopicFormType }
    symbb.extensionbbcode.manager:
        class: SymBB\Extension\BBCodeBundle\DependencyInjection\BBCodeManager
        arguments: ['@service_container']
    symbb.extensionbbcode.manager.twig:
        twig.extension.symbb.extensionbbcode.manager.twig:
        class: SymBB\Extension\BBCodeBundle\Twig\BBCodeManagerExtension
        arguments: ['@symbb.extensionbbcode.manager']
        tags:
            - { name: twig.extension } 
            
            