services:
    symbb.listener.post.rating:
        class: SymBB\Post\RatingBundle\EventListener\TemplateListener
        tags:
            - { name: kernel.event_listener, event: symbb.forum.after.text, method: afterText }
   
    symbb.post.rating.util:
        twig.extension.symbb.post.rating.util:
        class: SymBB\Post\RatingBundle\Twig\UtilExtension
        arguments: ['@doctrine', '@security.context']
        tags:
            - { name: twig.extension } 