_symbb_index:
    pattern:  /
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }
    
_symbb_forum_index:
    pattern:  /forum
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }
    
_symbb_forum_show:
    pattern:  /forum/f-{name}/{id}
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forumShow }
    
_symbb_forum_topic_show:
    pattern:  /forum/t-{name}/{id}
    defaults: { _controller: SymBBCoreForumBundle:FrontendTopic:show}
    
_symbb_forum_post_evaluate:
    pattern:  /forum/evaluate/p-{name}/{id}/{like}
    defaults: { _controller: SymBBCoreForumBundle:FrontendTopic:evaluatePost}