_symbb_index:
    pattern:  /portal
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }
    
_symbb_forum_index:
    pattern:  /
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forum }
    
_symbb_forum_show:
    pattern:  /f-{name}/{id}
    defaults: { _controller: SymBBCoreForumBundle:Frontend:forumShow }
    
_symbb_forum_topic_show:
    pattern:  /t-{name}/{id}
    defaults: { _controller: SymBBCoreForumBundle:FrontendTopic:show}
    
_symbb_new_post:
    pattern:  /t-{name}/{topic}/answer
    defaults: { _controller: SymBBCoreForumBundle:FrontendPost:new}
    
    